[tool.poetry]
name = "dopetracks"
version = "0.2.1"
description = ""
authors = ["namarks <nmarkspdx@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["../.."]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"